include: package:very_good_analysis/analysis_options.6.0.0.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
    avoid_positional_boolean_parameters: false
